FAQS/faq/urls.py
from django.db import router
from django.urls.conf import path,include

from rest_framework.routers import DefaultRouter

# pure django
from .views import IndexViews,QuestionDetail,QuestionCreate,AnswerQuestion

# rest api
from .apiviews import QuestionViewSet,AnswerList,LoginView,AnswerCreate,UserCreate

router = DefaultRouter()

router.register('faqapi',QuestionViewSet,basename='faqapi')

app_name = "faq"

urlpatterns = [
    # api login
    path('login/', LoginView.as_view(), name='login'),

    path('users/create', UserCreate.as_view(), name="user_create"),
    path('faqapi/<int:pk>/answers/', AnswerList.as_view(),name='answer_list'),
    path('faqapi/<int:pk>/answers/create/', AnswerCreate.as_view(),name='answer_create'),
    # path()
    path('faq/', IndexViews.as_view(), name='index'),
    path('faq/create/', QuestionCreate.as_view(), name='question_create'),
    path('faq/<int:pk>/', QuestionDetail.as_view(),name='question_detail'),
    path('faq/<int:question_id>/answers/create/', AnswerQuestion.as_view(), name='answer_question')
    
]

urlpatterns += router.urls

FAQS/faqs/urls.py
from django.contrib import admin
from django.urls import include, re_path

urlpatterns = [
    # re_path('admin/', admin.site.urls),
    re_path(r'admin/', admin.site.urls),
    re_path(r'^', include('faq.urls')),
    # website login
    re_path('accounts/', include("django.contrib.auth.urls")),
]

FAQS/faq/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User



class Question(models.Model):
    question_text = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created_by = models.ForeignKey(User, on_delete=models.PROTECT)
    pub_date = models.DateTimeField(auto_now=True)
    
    def __str__(self):
        return self.question_text

    def get_absolute_url(self):
        return reverse('faq:question_detail', kwargs={'pk': self.pk})

    # answercount = models.IntegerField(default=0)

    # @property
    # def _get_answer_count(self):
    #     """return answer count"""
    #     return self.answer_set.count()

    # def save(self, force_insert, force_update, using, update_fields):
    #     self.answercount = self._get_answer_count()
    #     return super().save(force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)
    # answercount = property(_get_answer_count)
    # answercount = 

class Answer(models.Model):
    # question = models.ForeignKey(Question, related_name='answers', on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer_text = models.TextField(blank=False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    pub_date = models.DateTimeField(auto_now=True)

FAQS/faq/forms.py
from django import forms

class AnswerForm(forms.Form):
    answer_text = forms.CharField(widget=forms.Textarea)

FAQS/faq/views.py
# from django import views
# from django.db import models
from django.http.response import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_list_or_404,get_object_or_404, redirect,render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View

from django.db.models import Count,Q


from .models import Question,Answer
from .serializers import QuestionSerializer,AnswerSerializer

# these views are for public content

class IndexViews(generic.ListView):
    template_name = "faq/index.html"
    context_object_name = "latest_question_list"

    paginate_by = 10
    def get_queryset(self):
        # return super().get_queryset()
        if self.request.GET.get('answered'):
        
            # print("q izy")
            mquestions = Question.objects.annotate(num_answers=Count('answer'))
            q = mquestions.filter(num_answers__gte=1).order_by('pub_date')
            return q
        else:
            # print("q tsy izy")
            return Question.objects.order_by('-pub_date')
            
        #for filter purpose
        # return 


# def index(request):
#     # return HttpResponse("index here")
#     questions = Question.objects.order_by('-pub_date')[:5]
#     return render(request,"faq/index.html",{})

    # def get(self, request, *args, **kwargs):
    #     print(args,kwargs,request.GET.get('answered'))
    #     if request.GET.get('answered'):
    #     return super().get(request, *args, **kwargs)
    

class QuestionDetail(generic.DetailView):
    model = Question
    template_name = "faq/detail.html"

    


class QuestionCreate(LoginRequiredMixin,generic.CreateView):
# class QuestionCreate(generic.CreateView):
    model = Question
    fields = ["question_text","description"]
    # fields = "__all__"
    template_name = "faq/submit_question.html"

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)

    
# class AnswerCreate(LoginRequiredMixin,generic.CreateView):
#     model = Answer
#     fields = ["answer_text"]
#     template_name = "faq/detail.html"

# def answer_question(request, question_id):
#     question = get_object_or_404(Question,pk=question_id)
#     print(question)
#     # return redirect(Question.objects.get(pk=question_id).get_absolute_url())

class AnswerQuestion(LoginRequiredMixin,View):
    
    login_url = 'accounts/login/'
    redirect_field_name = 'redirect_to'

    def post(self,request,question_id):
        created_by = request.user.id
        answer_text = request.POST.get("answer_text")
        print(created_by,answer_text)

        serializer = AnswerSerializer(data={"question":question_id,"answer_text":answer_text,"created_by":created_by})
        if(serializer.is_valid()):
            serializer.save()

        return redirect(Question.objects.get(pk=question_id).get_absolute_url())
        

    # needed for allowing GET
    def get(self,request, question_id):
        # render(request, "faq/detail.html")
        redirect(Question.objects.get(pk=question_id).get_absolute_url())

FAQS/faq/templates/faq/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet"  href="{% static 'faq/css/bootstrap.css' %}"/>    
    <script src="{% static 'faq/js/bootstrap.js' %}"></script>
    <title>{% block title %} Django FAQ {% endblock %}</title>
</head>

<body>
    {% if messages %}
    {% for message in messages %}
    <span class="alert-danger">{{message}}</span>
    {% endfor %}
    {% endif %}
    <div id="navbar" class="container-fluid p-4 bg-light">
        {% block navbar %}
        <ul class="nav justify-content-end">
            {% comment %} <li><a href="/">Home</a></li> {% endcomment %}
            <li class="nav-item"><a class="nav-link" href="{% url 'faq:question_create' %}">ask a question</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'faq:index' %}">all questions</a></li>
            <li class="nav-item"><a class="nav-link" href="{% url 'faq:index' %}?answered=true">answered questions</a></li>
            {% if user.is_authenticated %}
            <li class="nav-item"> <span class="nav-link">{{ user.username }}</span> </li>
            <li class="nav-item"><a class="nav-link alert-info" href="{% url 'logout' %}">logout</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link alert-primary" href="{% url 'login' %}">login</a></li>
            {% endif %}
        
        </ul>
        {% endblock %}
    </div>

    <div id="content" class="container">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

FAQS/faq/templates/faq/detail.html
{% extends 'faq/base.html' %}

{% block content %}
<div class="row">
    <div class="col-4">
        {% comment %} <form action="{% url 'faq:answer_question' %}"> {% endcomment %}
        {% comment %} <form action="." method="POST"> {% endcomment %}
        <form action="{% url 'faq:answer_question' question.id %}" method="POST" class="form-control">
        {% csrf_token %}
        <label for="answer_text"/>
        <textarea id="answer_text" name="answer_text" placehoder="your answer here" class="form-control-lg"></textarea>
        <input type="submit" eval="submit answer"/>
        </form>
    </div>
    <div class="col-8">
        <div class="p-5">
            <h3>{{question}}</h3>
            <p> {{question.description}} </p>
        </div>
        {% for answer in question.answer_set.all %}
        <div class="row p-2">
            <p>{{answer.answer_text}}  -- {{answer.created_by}} - {{answer.pub_date}}</p>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

FAQS/faq/templates/faq/index.html
{% extends 'faq/base.html' %}

{% block title %}{{block.super}} : index {% endblock %}


{% block content %}
<div class="container container-sm">
<table class="table table-borderless p-3">
<thead>
  <tr>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
{% for question in latest_question_list %}
  <tr>
    <td><a href="{% url 'faq:question_detail' question.id %}"><span>{{ question.question_text }}</span></a></td>
    <td><span>{{ question.answer_set.all.count }}  answer{% if question.answer_set.all.count > 1 %}s{% endif %}</span></td>
  </tr>
{% endfor %}
  {% if is_paginated %}
      <div class="pagination">
        <span class="page-links">
            {% if page_obj.has_previous %}
                <a href="/faq?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}
            <span class="page-current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>
            {% if page_obj.has_next %}
                <a href="/faq?page={{ page_obj.next_page_number }}">next</a>
            {% endif %}
        </span>
      </div>
  {% endif %}
</tbody>    
</table>
</div>
{% endblock content %}

FAQS/faq/templates/faq/submit_question.html
{% extends 'faq/base.html' %}

{% block title %}{{ block.super }}: Add Question{% endblock %}

{% block content %}
<h3>Submit your question</h3>
<p>
  Use this form to submit a question (and optionally a corresponding answer)
  that you would like to see added to the FAQs on this site.
</p>
<form action="." method="POST">
  {% csrf_token %}
  <table>
    {{ form.as_table }}
  </table>
  <input type="submit" value="Submit"/>
</form>
{% endblock %}